# Generated by Django 4.2.11 on 2026-03-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scamdataset',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
