# Generated by Django 4.2.11 on 2026-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_scamdataset_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
                ('last_trained', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
